title: Pandemics, Academics, Gender and Race
email: jeremy@virginia.edu
description: >- # this means to ignore newlines until "baseurl:"
  An ongoing research collaborative, sharing an annotated bibliography
  on the intersections of pandemics, race, and gender in the academy.
baseurl: ""
url: "https://pandemicacademics.github.io"

plugins: ['jekyll/scholar']

scholar:
  style: modern-language-association
  sort_by: author,year
  sort_order: ascending,descending